name: "Build Theme Alpha OpenWrt SDK"
on:
  repository_dispatch:
  workflow_dispatch:
  push:

jobs:
  job_build_alpha:
    name: Build Alpha Theme (master)
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          echo "Install packages"
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
      - name: Cache openwrt SDK
        id: cache-sdk
        uses: actions/cache@main
        with:
          path: sdk
          key: openwrt-sdk-21.02-x86-64

      - name: Initialization environment
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        env:
          url_sdk: https://archive.openwrt.org/releases/21.02.5/targets/x86/64/openwrt-sdk-21.02.5-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        run: |
          wget ${{ env.url_sdk }}
          file_name=$(echo ${{env.url_sdk}} | awk -F/ '{print $NF}')
          mkdir sdk && tar -xJf $file_name -C ./sdk --strip-components=1
          cd sdk  
          echo "src-git base https://github.com/openwrt/openwrt.git;openwrt-21.02" > feeds.conf
          echo "src-git-full packages https://github.com/openwrt/packages.git;openwrt-21.02" >> feeds.conf
          echo "src-git-full luci https://git.openwrt.org/project/luci.git;openwrt-21.02" >> feeds.conf
          echo "src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-21.02"  >> feeds.conf
          git clone -b master https://github.com/${{ github.repository }}.git package/downloads/luci-theme-alpha
          ./scripts/feeds update -a
          echo "CONFIG_PACKAGE_luci-theme-alpha=m" > .config
          ./scripts/feeds install -d n luci-theme-alpha
          make download -j8
      - name: Configure Alpha Theme (master)
        run: |
          cd sdk
          git clone --depth 1 -b master https://github.com/${{ github.repository }}.git package/downloads/luci-theme-alpha
          ./scripts/feeds install luci-theme-alpha
          echo "CONFIG_ALL_NONSHARED=n" > .config
          echo "CONFIG_ALL_KMODS=n" >> .config
          echo "CONFIG_ALL=n" >> .config
          echo "CONFIG_AUTOREMOVE=n" >> .config
          echo "CONFIG_LUCI_LANG_zh_Hans=n" >> .config
          echo "CONFIG_PACKAGE_luci-theme-alpha=m" >> .config
          make defconfig
      - name: Compile Alpha Theme (master)
        id: compile
        run: |
          cd sdk
          echo "make package/luci-theme-alpha/{clean,compile} -j$(nproc)"
          make package/luci-theme-alpha/{clean,compile} -j$(nproc)
          mv bin/packages/x86_64/base/ ../
          rm .config .config.old
          cd ..
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: Artifact
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success'
        with:
          name: luci-theme
          path: ${{ env.FIRMWARE }}/base/luci-theme*.ipk

      - name: Delete workflow runs
        uses: AoThen/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 5
